version: "3.7"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5435:5432'